[project]
name = "uon-course-explorer"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "num2words>=0.5.13",
    "requests>=2.32.3",
    "werkzeug>=3.1.3",
]
